import type { INodeProperties } from 'n8n-workflow';

export const checkoutOperations: INodeProperties = {
  displayName: 'Operation',
  name: 'operation',
  type: 'options',
  noDataExpression: true,
  displayOptions: {
    show: { resource: ['checkout'] },
  },
  options: [
    {
      name: 'Create',
      value: 'create',
      action: 'Create a checkout',
      description: 'Create a new checkout link',
    },
    {
      name: 'Get',
      value: 'get',
      action: 'Get a checkout',
      description: 'Retrieve a single checkout by ID',
    },
    {
      name: 'Get Many',
      value: 'getAll',
      action: 'Get many checkouts',
      description: 'Retrieve multiple checkouts',
    },
    {
      name: 'Update',
      value: 'update',
      action: 'Update a checkout',
      description: 'Update an existing checkout (e.g. change expiry or prefilled data)',
    },
    {
      name: 'Delete',
      value: 'delete',
      action: 'Delete a checkout',
      description: 'Delete a checkout link',
    },
  ],
  default: 'create',
};

export const checkoutFields: INodeProperties[] = [
  // Checkout ID for Get operation
  {
    displayName: 'Checkout ID',
    name: 'checkoutId',
    type: 'string',
    required: true,
    default: '',
    description: 'The ID of the checkout to retrieve',
    displayOptions: {
      show: { resource: ['checkout'], operation: ['get', 'update', 'delete'] },
    },
  },
  // Create Fields
  {
    displayName: 'Store',
    name: 'checkoutStoreId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getStores',
    },
    required: true,
    default: '',
    description:
      'The store to create the checkout for. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
    displayOptions: {
      show: { resource: ['checkout'], operation: ['create'] },
    },
  },
  {
    displayName: 'Variant',
    name: 'checkoutVariantId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getVariants',
      loadOptionsDependsOn: ['checkoutStoreId'],
    },
    required: true,
    default: '',
    description:
      'The variant to checkout. Filtered by the selected store. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
    displayOptions: {
      show: { resource: ['checkout'], operation: ['create'] },
    },
  },
  {
    displayName: 'Additional Options',
    name: 'additionalOptions',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: { resource: ['checkout'], operation: ['create'] },
    },
    options: [
      {
        displayName: 'Custom Price',
        name: 'customPrice',
        type: 'number',
        default: 0,
        description: 'Custom price in cents (for pay-what-you-want products)',
      },
      {
        displayName: 'Discount Code',
        name: 'discountCode',
        type: 'string',
        default: '',
        description: 'Discount code to apply to the checkout',
      },
      {
        displayName: 'Customer Email',
        name: 'email',
        type: 'string',
        default: '',
        description: 'Pre-fill customer email',
      },
      {
        displayName: 'Customer Name',
        name: 'name',
        type: 'string',
        default: '',
        description: 'Pre-fill customer name',
      },
      {
        displayName: 'Redirect URL',
        name: 'redirectUrl',
        type: 'string',
        default: '',
        description: 'URL to redirect after successful purchase',
      },
      {
        displayName: 'Receipt Button Text',
        name: 'receiptButtonText',
        type: 'string',
        default: '',
        description: 'Custom text for receipt button',
      },
      {
        displayName: 'Receipt Link URL',
        name: 'receiptLinkUrl',
        type: 'string',
        default: '',
        description: 'Custom URL for receipt button',
      },
      {
        displayName: 'Receipt Thank You Note',
        name: 'receiptThankYouNote',
        type: 'string',
        default: '',
        description: 'Custom thank you note on receipt',
      },
      {
        displayName: 'Custom Data',
        name: 'customData',
        type: 'json',
        default: '{}',
        description: 'Custom data to attach to the checkout (will be passed to webhooks)',
      },
      {
        displayName: 'Expires At',
        name: 'expiresAt',
        type: 'dateTime',
        default: '',
        description: 'When the checkout link expires (ISO 8601 format)',
      },
      {
        displayName: 'Skip Trial',
        name: 'skipTrial',
        type: 'boolean',
        default: false,
        description: 'Whether to skip any free trial period for subscriptions',
      },
      {
        displayName: 'Test Mode',
        name: 'testMode',
        type: 'boolean',
        default: false,
        description: 'Whether this is a test checkout',
      },
      {
        displayName: 'Billing Address Country',
        name: 'billingAddressCountry',
        type: 'string',
        default: '',
        description: 'Pre-fill billing country (ISO 3166-1 alpha-2 code, e.g., "US")',
      },
      {
        displayName: 'Billing Address Zip',
        name: 'billingAddressZip',
        type: 'string',
        default: '',
        description: 'Pre-fill billing zip/postal code',
      },
      {
        displayName: 'Tax Number',
        name: 'taxNumber',
        type: 'string',
        default: '',
        description: 'Pre-fill tax/VAT number',
      },
      {
        displayName: 'Variant Quantities',
        name: 'variantQuantities',
        type: 'json',
        default: '[]',
        description:
          'Array of variant quantity overrides as JSON (e.g., [{"variant_id": 1, "quantity": 2}])',
      },
      {
        displayName: 'Product Name Override',
        name: 'productName',
        type: 'string',
        default: '',
        description: 'Override the product name displayed at checkout',
      },
      {
        displayName: 'Product Description Override',
        name: 'productDescription',
        type: 'string',
        default: '',
        description: 'Override the product description displayed at checkout',
      },
      {
        displayName: 'Product Media URLs',
        name: 'productMedia',
        type: 'string',
        default: '',
        description: 'Comma-separated list of image URLs to display at checkout',
      },
      {
        displayName: 'Enabled Variants',
        name: 'enabledVariants',
        type: 'string',
        default: '',
        description: 'Comma-separated list of variant IDs to enable for product selection',
      },
      {
        displayName: 'Shorten URL',
        name: 'shortenUrl',
        type: 'boolean',
        default: false,
        description:
          'Whether to generate a shortened checkout URL using the Lemon Squeezy short URL format. The shortened URL will be returned in the checkout_short_url field.',
      },
    ],
  },
  // Checkout Options
  {
    displayName: 'Checkout Display Options',
    name: 'checkoutOptions',
    type: 'collection',
    placeholder: 'Add Display Option',
    default: {},
    displayOptions: {
      show: { resource: ['checkout'], operation: ['create'] },
    },
    options: [
      {
        displayName: 'Active State Color',
        name: 'activeStateColor',
        type: 'string',
        default: '',
        description: 'Active state color hex code',
        placeholder: '#7c3aed',
      },
      {
        displayName: 'Background Color',
        name: 'backgroundColor',
        type: 'string',
        default: '',
        description: 'Background color hex code',
        placeholder: '#ffffff',
      },
      {
        displayName: 'Borders Color',
        name: 'bordersColor',
        type: 'string',
        default: '',
        description: 'Borders color hex code',
        placeholder: '#e5e7eb',
      },
      {
        displayName: 'Button Color',
        name: 'buttonColor',
        type: 'string',
        default: '',
        description: 'Button background color hex code',
        placeholder: '#7c3aed',
      },
      {
        displayName: 'Button Text Color',
        name: 'buttonTextColor',
        type: 'string',
        default: '',
        description: 'Button text color hex code',
        placeholder: '#ffffff',
      },
      {
        displayName: 'Checkbox Color',
        name: 'checkboxColor',
        type: 'string',
        default: '',
        description: 'Checkbox color hex code',
        placeholder: '#7c3aed',
      },
      {
        displayName: 'Embed Mode',
        name: 'embed',
        type: 'boolean',
        default: false,
        description: 'Whether checkout is embedded',
      },
      {
        displayName: 'Headings Color',
        name: 'headingsColor',
        type: 'string',
        default: '',
        description: 'Headings color hex code',
        placeholder: '#1a1a2e',
      },
      {
        displayName: 'Links Color',
        name: 'linksColor',
        type: 'string',
        default: '',
        description: 'Links color hex code',
        placeholder: '#7c3aed',
      },
      {
        displayName: 'Primary Text Color',
        name: 'primaryTextColor',
        type: 'string',
        default: '',
        description: 'Primary text color hex code',
        placeholder: '#1a1a2e',
      },
      {
        displayName: 'Secondary Text Color',
        name: 'secondaryTextColor',
        type: 'string',
        default: '',
        description: 'Secondary text color hex code',
        placeholder: '#6b7280',
      },
      {
        displayName: 'Show Description',
        name: 'desc',
        type: 'boolean',
        default: true,
        description: 'Whether to show the product description',
      },
      {
        displayName: 'Show Discount Field',
        name: 'discount',
        type: 'boolean',
        default: true,
        description: 'Whether to show the discount code field',
      },
      {
        displayName: 'Show Logo',
        name: 'logo',
        type: 'boolean',
        default: true,
        description: 'Whether to show the store logo',
      },
      {
        displayName: 'Show Media',
        name: 'media',
        type: 'boolean',
        default: true,
        description: 'Whether to show product media',
      },
      {
        displayName: 'Show Subscription Preview',
        name: 'subscriptionPreview',
        type: 'boolean',
        default: true,
        description: 'Whether to show subscription pricing preview text',
      },
      {
        displayName: 'Terms/Privacy Color',
        name: 'termsPrivacyColor',
        type: 'string',
        default: '',
        description: 'Terms and privacy link color hex code',
        placeholder: '#64748b',
      },
    ],
  },
  // Return All
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    default: false,
    description: 'Whether to return all results or only up to a given limit',
    displayOptions: {
      show: { resource: ['checkout'], operation: ['getAll'] },
    },
  },
  // Limit
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    default: 50,
    description: 'Max number of results to return',
    typeOptions: { minValue: 1, maxValue: 100 },
    displayOptions: {
      show: { resource: ['checkout'], operation: ['getAll'], returnAll: [false] },
    },
  },
  // Filters
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filter',
    default: {},
    displayOptions: {
      show: { resource: ['checkout'], operation: ['getAll'] },
    },
    options: [
      {
        displayName: 'Store ID',
        name: 'storeId',
        type: 'string',
        default: '',
        description: 'Filter by store ID',
      },
      {
        displayName: 'Variant ID',
        name: 'variantId',
        type: 'string',
        default: '',
        description: 'Filter by variant ID',
      },
    ],
  },
  // ── Update fields ─────────────────────────────────────────────────────────
  {
    displayName: 'Update Fields',
    name: 'updateFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: {
      show: { resource: ['checkout'], operation: ['update'] },
    },
    options: [
      {
        displayName: 'Custom Price (Cents)',
        name: 'customPrice',
        type: 'number',
        default: 0,
        typeOptions: { minValue: 0 },
        description: 'Override the product price for this checkout (in cents)',
      },
      {
        displayName: 'Discount Code',
        name: 'discountCode',
        type: 'string',
        default: '',
        description: 'Pre-fill a discount code for the customer',
      },
      {
        displayName: 'Email',
        name: 'email',
        type: 'string',
        default: '',
        description: 'Pre-fill the customer email address',
        placeholder: 'name@email.com',
      },
      {
        displayName: 'Expires At',
        name: 'expiresAt',
        type: 'dateTime',
        default: '',
        description: 'The new expiry date/time for the checkout link',
      },
      {
        displayName: 'Name',
        name: 'name',
        type: 'string',
        default: '',
        description: 'Pre-fill the customer name',
      },
    ],
  },
];
